### ISSUE TITLE
[catbuffer] Remove the need to rename structs when adding a new version

### ISSUE THREAD

**Issue by Momo10101** [symbol/symbol#9]
Currently the way to add a new version of a struct is to create a new struct with the same name as the old struct but appending a number which represents the struct version, like this:

```yaml
- comments: binary layout for a transfer transaction (V2)
  layout:
  - comments: ''
    disposition: const
    name: TRANSACTION_VERSION
    signedness: unsigned
    size: 1
    type: byte
    value: 2
  - comments: ''
    disposition: inline
    type: TransferTransaction
  - comments: number of attached mosaics
    name: mosaics_count
    signedness: unsigned
    size: 1
    type: byte
  - comments: attached mosaics notice that mosaic amount is multipled by transfer
      amount to get effective amount
    disposition: array
    name: mosaics
    size: mosaics_count
    sort_key: mosaic_id
    type: Mosaic
  name: TransferTransaction2
  type: struct
```

We should remove the need for adding the version number to a struct name since it is already defined as a field. The generator internally can add name mangling to resolve version names when generating code. Something like this for example: TransferTransaction, TransferTransactionV2, TransferTransactionV3, etc..

This is also related to this issue:
https://github.com/symbol/catbuffer-parser/issues/28
